#!/bin/bash

output=$(xsct)
temp=$(echo $output | awk '{print $5}')
bright=$(echo $output | awk '{print $6}')

cat > ~/.config/i3/bright_temp_on_shutdown <<EOF
#!/bin/bash

xsct $temp $bright
EOF

chmod +x ~/.config/i3/bright_temp_on_shutdown

case $1 in
  "logout"  ) i3-msg exit ;;
  "poweroff") systemctl poweroff ;;
  "reboot"  ) systemctl reboot ;;
  "bios"    ) systemctl reboot --firmware-setup ;;
esac
