#!/usr/bin/ruby
current = `pactl get-default-sink`.chomp
sinks = `pactl list sinks short`.lines.map {|line| line.split[1]}

`pactl set-default-sink '#{sinks[(sinks.index(current) + 1) % sinks.size]}'`
