#!/usr/bin/ruby

speakers = "alsa_output.pci-0000_03_00.1.hdmi-stereo"
headphones = "alsa_output.pci-0000_12_00.6.analog-stereo"
current_sink = `pactl get-default-sink`.chomp!

if current_sink == speakers then `pactl set-default-sink #{headphones}`
                            else `pactl set-default-sink #{speakers}`
end
