#!/usr/bin/bash

mkdir -p old-versions
mkdir -p zips


if [ -d 'base' ]; then
  # rename old dr dir with its version
  version=$(head -1 base/CHANGELOG-CURR.txt | cut -c 3-)
  mv base/ old-versions/$version
fi

# unzips to 2 files `dragonruby-linux-amd64/` and `.itch.toml`
unzip dragonruby-gtk-linux-amd64.zip
mv dragonruby-linux-amd64/ base/
rm .itch.toml

# replace default font with monogram font
mv base/font.ttf base/font-og.ttf
cp font.ttf base/font.ttf

# move zip file to zips
prefix=$(head -1 base/CHANGELOG-CURR.txt | cut -c 3-)
filename="dragonruby-gtk-linux-amd64.zip"
mv dragonruby-gtk-linux-amd64.zip zips/${prefix}${filename}
