#!/usr/bin/bash

unzip dragonruby-gtk-linux-amd64.zip
rm .itch.toml

if [ -d 'base' ]; then

# move projects to new dr dir
mv base/proj/ dragonruby-linux-amd64/proj/
# move font and change old font name
mv dragonruby-linux-amd64/font.ttf dragonruby-linux-amd64/font-og.ttf
cp font.ttf dragonruby-linux-amd64/font.ttf
# move newproj script
mv base/newproj dragonruby-linux-amd64/newproj
# rename old dr dir with version
version="`head -1 base/CHANGELOG-CURR.txt | cut -c 3-`"
mv base/ old-versions/$version

else # for first install in a computer

# make new dr dir
mkdir dragonruby-linux-amd64/proj
# add smaller font(as in file size, not text size)
mv dragonruby-linux-amd64/font.ttf dragonruby-linux-amd64/font-og.ttf
cp font.ttf dragonruby-linux-amd64/font.ttf
# create file for initializing a new project
cat > dragonruby-linux-amd64/newproj <<EOF
#!/usr/bin/sh

if [ -z \$1 ]; then
  echo "Failed: No directory supplied"
elif [ -d proj/\$1 ]; then
  echo "Failed: Directory already exists"
else
  cp -r mygame/ proj/\$1
fi
EOF

chmod +x dragonruby-linux-amd64/newproj

fi

mv dragonruby-linux-amd64/ base/

prefix=`head -1 base/CHANGELOG-CURR.txt | cut -c 3-`
filename="dragonruby-gtk-linux-amd64.zip"
mv dragonruby-gtk-linux-amd64.zip zips/${prefix}${filename}
